#**Numpy**: 
It is anumerical python and it is used for the manipulation of a number.

In [ ]:
import numpy as np

# Difference between Numpy and List:-

Numpy:   ---    &    ---   List:

1.   **Size** : Numpy DS take up less space.
2.   **Performance**: They have need for speed and are faster than lists.
3.   **Functionality**: SciPy and NumPy have optimizes dunctions such as linear algebra operations built in.





---
### **`Program Implementation:`**
We can use **timeit** to find the running time(avg/mean).


**%timeit** - For getting the execution time of single statement.





**%%timeit** - For multiline execution time

In [ ]:
%timeit[i**2 for i in range(1,11)] #List

The slowest run took 6.16 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.9 µs per loop


In [ ]:
%timeit np.arange(1,11)**2

The slowest run took 2280.44 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.73 µs per loop


*In this case you'll find that numpy array is taking much lesser time than that of list.* 



---
# Searching Arrays in Numpy:-

  We can search a value in an array and if the value is found the concerned index is returned.
  To search an array, we use **where()** method.










In [ ]:
srch_arr = np.array([10,20,30,40,50,40,40])
x1 = np.where(srch_arr == 40)
x1

(array([3, 5, 6]),)

### `Searchsorted() :-`


This method performs a Binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

this searching is from left to right.



In [ ]:
a = np.array([3,5,8,9,13])
x = np.searchsorted(a,10)
x

4

But if we want ro perform from **right side**.

In [ ]:
a = np.array([2,3,5,8,9,13])
x = np.searchsorted(a,7 ,side = 'right')
x

3



---



#**1D array:**

In [ ]:

my_list = [1,2,3,5]
n = np.array(my_list)


In [ ]:
type(n)
type(my_list)

list



---



---

#**Multi-Dimensional arrays:**

In [ ]:
 arr = np.array([[1,2,3],[4,5,6],[7,7,8,]])
 arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 7, 8]])

In [ ]:
arr.shape

(3, 3)

it is a range wher we give a range from 0to 10;

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z = np.arange(0,50)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
z.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
len(z)

50

In [ ]:
new_variable = z.reshape(5,10)
new_variable

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
for i in range(0, 10,2):
    print(i)

0
2
4
6
8


In [ ]:
m = np.zeros((3,3))
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
m1 = np.ones((3,2))
m1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a = np.eye(6)
a
# If you see the diagonals reight of the eye or it acutally
# helps us to generate one-sisded diagonals 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

***linespace function returns values between a given range
and with a same gap between consecutive elements.***

In [ ]:
b = np.linspace(0,7,10)
b

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [ ]:
len(b)

10

In [ ]:
b.resize(10,1)
b

array([[0.        ],
       [0.77777778],
       [1.55555556],
       [2.33333333],
       [3.11111111],
       [3.88888889],
       [4.66666667],
       [5.44444444],
       [6.22222222],
       [7.        ]])



---



---



#**Generate some random values:**

 np.random.rand(3,2) :  Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
# help(np.random)

In [ ]:
np.random.rand(3,2)

array([[0.21535218, 0.94658827],
       [0.95866165, 0.87237558],
       [0.53954517, 0.98813372]])

np.random.randn(3,3):  It Return a sample (or samples) from the “standard normal” distribution.

In [ ]:
np.random.randn(3,3)

array([[ 1.10880938, -0.70818333,  0.41068113],
       [-1.19973651,  1.1959191 ,  0.72004483],
       [-0.09208281,  1.3683045 ,  0.98496721]])

In [ ]:
np.random.ranf(5)

array([0.1990109 , 0.51468933, 0.35989805, 0.29590958, 0.45810207])

In [ ]:
# np.random.randint(10,20 ,size=(5,9))
np.random.randint(5,size = 2)

array([3, 3])

## Seed function:


```
We know that randint() function generates random numbers.
Everytime we run the program,new set of random number 
is generated. But what if we want to fix the generation
of this random number .In this case we use 'seed', 
this generates fix set of random numbers.  
```



In [ ]:
#example: it won't change until you change the value
np.random.seed(13)  #important statement
arr = np.random.randint(1,100,12)
# arr.size  #for size
arr

array([83, 49, 75, 17, 99, 26, 59, 27, 67, 47, 55, 78])

 **Now it will return the same random numbers till we change the integer as passed to the seed at any computer**

##### Creating 2D array with fixed data type

In [ ]:
#example
np.random.seed(13)  #important statement
arr1 = np.random.randint(1,100,12).reshape(4,3)
# arr.size  #for size
arr

array([83, 49, 75, 17, 99, 26, 59, 27, 67, 47, 55, 78])

In [ ]:
np.sum(arr1)

682

In [ ]:
np.min(arr1)

17

In [ ]:
np.max(arr1)

99

**Shuffle**:- It will change the position in the array

In [ ]:
np.random.shuffle(arr1)
arr1

array([[83, 49, 75],
       [47, 55, 78],
       [17, 99, 26],
       [59, 27, 67]])

**Unique**:- It display unique number of the array.

"Suppose you've a array function and there are some values
which are repeated or basically it will discard the 
duplicate value "

---

# **Q1**:- Remove all the duplicates from the array.
Ans: use unique function

#**Q2**:- Count total no of unique elements are present.
Ans: use unique function with .size

In [ ]:
np.unique([12,12,1,3,45,1,25,5,2])

array([ 1,  2,  3,  5, 12, 25, 45])

**Unique().size**:- It counts the unique count of elements.

In [ ]:
np.unique([ 1,  2,  3,  5, 12, 25, 45]).size

7

#Index and Slicing

In [ ]:
ans=np.random.randint(4,15,7)
ans

array([ 8,  6,  4,  7,  9,  7, 10])

In [ ]:
ans[1]

6

In [ ]:
ans[-1]

10

In [ ]:
ans[3:5]

array([7, 9])

In [ ]:
ans[-7:0]

array([], dtype=int64)

In [ ]:
ans[3:]

array([ 7,  9,  7, 10])

In [ ]:
ans[:3]

array([8, 6, 4])

In [ ]:
ans[:]

array([ 8,  6,  4,  7,  9,  7, 10])

In [ ]:
an = np.arange(36)
an

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
an.resize(6,6)
an

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
an[2:]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
an[2, 2:5]
# use : to select a range of rows or columns

array([14, 15, 16])

In [ ]:
an[2,3] 

15

In [ ]:
an[3:,3:]

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [ ]:
an[an<25]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
an[an>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

## **Broadcasting**

In [ ]:
an[an>25]=25 #casting all the value that are greater than 25
an

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [ ]:
an[1:5]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25]])



---





```
# This is formatted as code
```

## **Creating copy & view and their differences:**

**The Difference Between Copy and View :-**

1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.


2. The copy SHOULD NOT be affected by the changes made to the original array.


3. The view SHOULD be affected by the changes made to the original array.


**copy :-**

In [ ]:
an[3:,2:]

array([[20, 21, 22, 23],
       [25, 25, 25, 25],
       [25, 25, 25, 25]])

In [ ]:
an_copy = an.copy()
an_copy #if you have to change your data but
#  you don't wanna change your original data that's why you create a copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])



---

**view :-**

In [ ]:
view1 = np.array([91,2,3])
x = view1.view()
x[0] = 1
view1

array([1, 2, 3])

In [ ]:
x

array([1, 2, 3])



---



# Matrix


In [ ]:
eg_matrix = np.array(([1,2,3,4],[4,5,6,4],[7,8,9,8]))

In [ ]:
eg_matrix

array([[1, 2, 3, 4],
       [4, 5, 6, 4],
       [7, 8, 9, 8]])

In [ ]:
eg_matrix[1][2]

6

In [ ]:
[eg_matrix < 7]

[array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False, False, False, False]])]

In [ ]:
eg_matrix[eg_matrix >7]

array([8, 9, 8])

In [ ]:
eg_matrix[eg_matrix < 7]

array([1, 2, 3, 4, 4, 5, 6, 4])

In [ ]:
eg_matrix.mean()

5.083333333333333

In [ ]:
eg_matrix.std()

2.43099202430247

In [ ]:
eg_matrix.var()

5.909722222222222

In [ ]:
eg1=np.matrix([[5,6,7],[4,6]])
eg1

/usr/local/lib/python3.7/dist-packages/numpy/matrixlib/defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)


matrix([[list([5, 6, 7]), list([4, 6])]], dtype=object)



---



## **Numpy for Statistical Operations:**


1.   amin():-   `It finds the minimum value alon a specified axis.`
---
2.   amax():-   `It finda the maximum value along a specified axis.`
---
3.   mean():-   `It finds the maximum value along a specified axis.`
---
4.   std():-    `It finds the standard deviation.`
---
5.   median():- `It find the mediian value of the dataset.`
---
6.   var :-     `It determines the variance.`
---
7.   average():- `It determines the weighted average.`
---
8.   ptp():-  `It returns the peak to peak value for a range of values along an axis.`
---
9.   percentile():-  `It determines the Nth percentile of data along the specified axis.`
---
10.  argmin():- `It returns the position of minimum number.`
---
11.  agrmax():- `It returns the position of maximum number.`
---
12.  sqrt():- `It returns the square root of every number.`
---
13.  sin():- `It returns the sin value of every number.`
---
14.  cos():-  `It returns the cos value of every number.`
---
15.  sum():- `It is used for finding the sum value of an array.`
---


In [ ]:
A = np.array([[11,12,13],[14,12,16],[14,15,16]])
A

array([[11, 12, 13],
       [14, 12, 16],
       [14, 15, 16]])

### `sum():-`

In [ ]:
np.sum(A)

123

In [ ]:
# finding the sum value alon a specified axis.
np.sum(A, axis = 0)

array([39, 39, 45])

In [ ]:
np.sum(A, axis = 1)

array([36, 42, 45])



---



### `amin():-`

In [ ]:
np.amin(A)

11

In [ ]:
np.amin(A, axis = 0)

array([11, 12, 13])

In [ ]:
np.amin(A, axis = 1)

array([11, 12, 14])



---



### `amax():-`

In [ ]:
np.amax(A)

16

In [ ]:
np.amax(A, axis = 0)

array([14, 15, 16])

In [ ]:
np.amax(A, axis = 1)

array([13, 16, 16])



---



### `mean():-`

In [ ]:
np.mean(A)

13.666666666666666

In [ ]:
np.mean(A, axis = 0)

array([13., 13., 15.])

In [ ]:
np.mean(A, axis = 1)

array([12., 14., 15.])



---



### `std():-`

In [ ]:
np.std(A)

1.699673171197595

In [ ]:
np.std(A, axis = 0)

array([1.41421356, 1.41421356, 1.41421356])

In [ ]:
np.std(A, axis = 1)

array([0.81649658, 1.63299316, 0.81649658])



---



### `Variance: var():-`

In [ ]:
np.var(A)

2.888888888888889

In [ ]:
np.var(A,axis = 0)

array([2., 2., 2.])

In [ ]:
np.var(A,axis = 1)

array([0.66666667, 2.66666667, 0.66666667])



---



### ` average():-`

In [ ]:
np.average(A)

13.666666666666666

In [ ]:
np.average(A, axis =0)

array([13., 13., 15.])

In [ ]:
np.average(A, axis =1)

array([12., 14., 15.])

when the weight values are not passed the avg value then the avg method works similar to the mean method.

In [ ]:
a = np.array([1,2,3,4,5,6,70])
np.average(a)

13.0

In [ ]:
#with weight gives weighted avg
wt = np.array([0.5,0.25,0.25,0.25,0.5,0.25,0.5])
np.average(a, weights= wt)

16.7



---



### `percentile():-`

In [ ]:
np.percentile(A, 10,1)

array([11.2, 12.4, 14.2])

In [ ]:
np.percentile(a, 10,axis = 0)

1.6

In [ ]:
np.percentile(A,30)

12.4

In [ ]:
np.percentile(a,30)

2.8



---



### `peak to peak : ptp():-`

In [ ]:
np.ptp(a,0) #0 is for the axis in the second argument

69



---

##**Stacking** :-


*   stack() function is used to join a sequence of same dimension arrays along a new axis.


*   The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.





---

***Stacking with 1D array:***

In [ ]:
stck = np.array([1,2,3,4])
stck2 = np.array([5,6,7,8])
stck

array([1, 2, 3, 4])

In [ ]:
stck2

array([5, 6, 7, 8])

In [ ]:
#It horizontally arranges the matrix
np.hstack((stck,stck2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#It vertically arranges the matrix
np.vstack((stck,stck2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

*just for fun*

In [ ]:
np.array((stck,stck2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])



---
***Stacking with 2D array:***


In [ ]:
np.random.seed(122)
stck_arr1= np.random.randint(1,21,9).reshape(3,3)
stck_arr2= np.random.randint(31,51,9).reshape(3,3)
stck_arr1

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [ ]:
stck_arr2

array([[40, 37, 45],
       [34, 35, 50],
       [50, 44, 31]])

In [ ]:
np.hstack((stck_arr1,stck_arr2))

array([[16, 11, 13, 40, 37, 45],
       [17, 13, 16, 34, 35, 50],
       [ 3, 16, 11, 50, 44, 31]])

In [ ]:
np.vstack((stck_arr1,stck_arr2))

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11],
       [40, 37, 45],
       [34, 35, 50],
       [50, 44, 31]])

*just for fun*

In [ ]:
np.array((stck_arr1,stck_arr2))

array([[[16, 11, 13],
        [17, 13, 16],
        [ 3, 16, 11]],

       [[40, 37, 45],
        [34, 35, 50],
        [50, 44, 31]]])



---



#**Data Frame:**



---



---



`skiprows:   it basically means to skip the row`

-
**`In 2D array`**:-

-
`axis = 0:   it means we drop in rows or removing rows frome the dataset`

-
`axis = 1:   it means we drop in cloumn or removing it from the dataset`
